# Generated by Django 4.1.5 on 2023-02-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_income',
        ),
    ]
