# Generated by Django 4.1.5 on 2023-02-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
