# Generated by Django 4.1.5 on 2023-02-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spendingtransaction',
            old_name='reciept',
            new_name='receipt',
        ),
    ]
