# Generated by Django 3.2.5 on 2023-01-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default=1, max_length=6),
        ),
    ]
