# Generated by Django 3.2.5 on 2023-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_notification_user_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default='unread', max_length=6),
        ),
    ]
