# Generated by Django 4.1.5 on 2023-02-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='07 February, 2023'),
        ),
    ]
