# Generated by Django 4.1.5 on 2023-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_user_toggle_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='toggle_privacy',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3),
        ),
    ]
