# Generated by Django 4.1.5 on 2023-02-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_rename_reciept_spendingtransaction_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingtransaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
