# Generated by Django 4.1.5 on 2023-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='time_limit_type',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='weekly', max_length=7),
        ),
        migrations.AlterField(
            model_name='limit',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
