# Generated by Django 4.1.5 on 2023-02-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0003_limit_time_limit_type_alter_limit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure.limit'),
        ),
    ]
