# Generated by Django 4.1.5 on 2023-02-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0003_alter_spendingtransaction_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='time_limit_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', max_length=7),
        ),
    ]
