# Generated by Django 4.1.5 on 2023-02-08 18:12

from django.db import migrations, models
import expenditure.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(validators=[expenditure.helpers.not_future]),
        ),
    ]
