# Generated by Django 4.1.5 on 2023-03-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='league_status',
            field=models.CharField(choices=[('bronze', 'bronze'), ('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum'), ('diamond', 'diamond')], default='bronze', max_length=8),
        ),
    ]
