# Generated by Django 4.1.5 on 2023-02-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_on',
            field=models.BooleanField(default=True),
        ),
    ]
