# Generated by Django 4.1.5 on 2023-02-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0006_user_notification_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_on',
        ),
        migrations.AddField(
            model_name='user',
            name='toggle_notification',
            field=models.CharField(choices=[('on', 'on'), ('off', 'off')], default='on', max_length=3),
        ),
    ]
