# Generated by Django 4.1.5 on 2023-02-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0007_remove_user_notification_on_user_toggle_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='toggle_notification',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=3),
        ),
    ]
